### ISSUE TITLE
Seems like the resource is broken

### ISSUE THREAD

**Issue by v-yarotsky** [timotto/concourse-npm-resource#5]
Started getting this recently:
<img width="708" alt="Screen Shot 2020-10-21 at 3 54 52 PM" src="https://user-images.githubusercontent.com/472161/96798515-e95b1180-13b5-11eb-809b-8b3810ba2520.png">

Probably related to https://github.com/timotto/concourse-npm-resource/pull/1

**Comment by ismferd** [comment]
Hi,

I have a similar problem since yesterday:
![image](https://user-images.githubusercontent.com/13453208/96840790-363cf780-144b-11eb-8987-9ac886c39fdd.png)

I tried adding `sudo chown -R 1000:1000 "/home/node/.npm"` but that didn't resolve my issue

**Comment by ismferd** [comment]
Do you have a workaround @v-yarotsky ?

**Comment by ismferd** [comment]
I would like to add that would be good tag your docker images in order to pin the version in our pipelines avoiding this kind of issues :D

**Comment by timotto** [comment]
The previous working version is now tagged as latest. I will fix the test suite. I will use either git commit hash or semver and git tags as docker image tags.

**Comment by timotto** [comment]
The docker image is now tagged with the git commit short ref.

Unfortunately [#6] still caused an `/opt/resource/in: line 36: package.json: Permission denied` error so I reverted the change to the Dockerfile and it now again runs as root.
